'use client';

import { useMemo, useState } from 'react';

type Recommendation = { rank: number; name: string; jp: string; area: string; detail: string; meta: string; tags: string[]; kind: '景點' | '美食'; image: string; accent: string };

const recommendations: Recommendation[] = [
  { rank: 1, name: '熊本城', jp: '熊本城', area: '熊本市中心', detail: '在銀杏城的石垣與天守閣之間，感受四百年歷史的壯麗。', meta: '建議停留 2–3 小時 · ¥800', tags: ['歷史文化', '必訪'], kind: '景點', image: '🏯', accent: 'from-[#263f36] to-[#5c806a]' },
  { rank: 2, name: '阿蘇火山口', jp: '阿蘇中岳火口', area: '阿蘇', detail: '站在世界最大的破火山口邊緣，看一眼不斷變化的火山色彩。', meta: '建議停留 1.5 小時 · 依管制開放', tags: ['自然景觀', '自駕推薦'], kind: '景點', image: '🌋', accent: 'from-[#405b58] to-[#9a8d6d]' },
  { rank: 3, name: '黑川溫泉', jp: '黒川温泉', area: '南小國町', detail: '穿上浴衣漫步溪谷，使用入湯手形巡訪三間特色溫泉。', meta: '建議停留 4–6 小時 · ¥1,300 起', tags: ['溫泉', '慢旅行'], kind: '景點', image: '♨️', accent: 'from-[#734d43] to-[#c59876]' },
  { rank: 1, name: '勝烈亭', jp: '勝烈亭 新市街本店', area: '熊本市中心', detail: '外酥內嫩的厚切黑豬里肌，搭配現磨芝麻醬，是在地人的日常。', meta: '午餐約 ¥1,500 · 常有排隊', tags: ['熊本黑豬', '排隊名店'], kind: '美食', image: '🥢', accent: 'from-[#8f4b32] to-[#d48c5d]' },
  { rank: 2, name: '菅乃屋', jp: '菅乃屋 上通店', area: '熊本市中心', detail: '熊本代表性的馬肉料理專門店，從刺身到炙燒一次品嚐。', meta: '晚餐約 ¥4,000 · 建議預約', tags: ['馬肉料理', '在地風味'], kind: '美食', image: '🍣', accent: 'from-[#613e4b] to-[#b57a80]' },
  { rank: 3, name: 'いまきん食堂', jp: 'いまきん食堂', area: '阿蘇內牧溫泉', detail: '來阿蘇不能錯過的赤牛丼，濃郁肉香與溫泉街氣氛完美相配。', meta: '午餐約 ¥1,800 · 週三公休', tags: ['赤牛丼', '阿蘇美食'], kind: '美食', image: '🍚', accent: 'from-[#8a633b] to-[#d0a65a]' },
];

export default function Home() {
  const [category, setCategory] = useState<'景點' | '美食'>('景點');
  const [selected, setSelected] = useState<string[]>([]);
  const [active, setActive] = useState<Recommendation | null>(null);
  const visible = useMemo(() => recommendations.filter((item) => item.kind === category), [category]);
  const toggle = (name: string) => setSelected((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]);

  return (
    <main className="min-h-screen bg-[#f5f2eb] text-[#18352c]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-10"><div className="flex items-center gap-3"><div className="brand-mark">K</div><div><div className="text-lg font-bold tracking-[0.18em]">KUMAMOTO</div><div className="text-[10px] uppercase tracking-[0.28em] text-[#85948b]">旅のしおり · Travel guide</div></div></div><div className="hidden items-center gap-8 text-sm font-medium text-[#648076] md:flex"><a href="#explore" className="text-[#18352c]">探索推薦</a><a href="#about">關於熊本</a><button className="rounded-full border border-[#ccd6cc] px-4 py-2">我的行程　{selected.length ? `(${selected.length})` : ''}</button></div><button className="md:hidden text-2xl" aria-label="開啟選單">☰</button></nav>
      <section className="relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-[#dbe7dc] px-6 pb-10 pt-12 sm:px-14 sm:pt-16"><div className="absolute -right-10 -top-24 h-72 w-72 rounded-full bg-[#c6d9c9] opacity-70" /><div className="absolute -bottom-36 right-28 h-80 w-80 rounded-full border-[42px] border-[#c4d7c5] opacity-70" /><div className="relative max-w-2xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.25em] text-[#6f897b]">Kumamoto, Japan · 2025 guide</p><h1 className="font-serif text-5xl font-medium leading-[1.08] tracking-tight text-[#17392e] sm:text-7xl">把熊本的<br /><em className="font-normal text-[#bb7654]">好風景</em> 放進行程。</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#557166]">從城下町到阿蘇火山，我們整理旅人最喜愛的景點與味道，幫你輕鬆拼出一趟剛剛好的熊本旅行。</p><a href="#explore" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#18352c] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#2d5647]">開始探索 <span>↓</span></a></div><div className="relative mt-12 flex items-end gap-3 sm:absolute sm:bottom-12 sm:right-12 sm:mt-0"><div className="hero-orb orb-one">阿蘇<br />⛰</div><div className="hero-orb orb-two">城下町<br />☼</div><div className="hero-orb orb-three">溫泉<br />♨</div></div></section>
      <section id="explore" className="mx-auto max-w-7xl px-5 py-14 sm:px-10 sm:py-20"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b37d61]">Curated for you</p><h2 className="mt-3 font-serif text-4xl text-[#18352c] sm:text-5xl">熊本人氣榜單</h2><p className="mt-3 text-[#6c8177]">目前最值得排進旅程的前三名</p></div><div className="flex rounded-full bg-[#e5e9e2] p-1.5"><button onClick={() => setCategory('景點')} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${category === '景點' ? 'bg-white text-[#18352c] shadow-sm' : 'text-[#7c9185]'}`}>熱門景點</button><button onClick={() => setCategory('美食')} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${category === '美食' ? 'bg-white text-[#18352c] shadow-sm' : 'text-[#7c9185]'}`}>美食推薦</button></div></div><div className="mt-9 grid gap-5 lg:grid-cols-3">{visible.map((item) => { const isSelected = selected.includes(item.name); return <article key={item.name} className={`group overflow-hidden rounded-3xl bg-white shadow-[0_8px_30px_rgba(50,73,60,0.06)] transition hover:-translate-y-1 hover:shadow-[0_16px_35px_rgba(50,73,60,0.12)] ${isSelected ? 'ring-2 ring-[#bb7654]' : ''}`}><button onClick={() => setActive(item)} className={`relative flex h-52 w-full items-center justify-center bg-gradient-to-br ${item.accent} text-[6.5rem]`} aria-label={`查看${item.name}詳情`}><span className="drop-shadow-md transition group-hover:scale-110">{item.image}</span><span className="absolute left-5 top-5 rounded-full bg-white/90 px-3 py-1 text-xs font-bold text-[#18352c]">NO. {item.rank}</span><span className="absolute bottom-4 left-5 rounded-full bg-[#18352c]/75 px-3 py-1 text-xs text-white">{item.area}</span></button><div className="p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{item.name}</h3><p className="mt-1 text-xs tracking-wide text-[#9aa9a0]">{item.jp}</p></div><button onClick={() => toggle(item.name)} className={`h-9 w-9 rounded-full border text-lg transition ${isSelected ? 'border-[#bb7654] bg-[#bb7654] text-white' : 'border-[#d8e0d8] text-[#a1b1a8] hover:border-[#bb7654]'}`} aria-label={isSelected ? `從行程移除${item.name}` : `加入行程${item.name}`}>{isSelected ? '✓' : '+'}</button></div><p className="mt-4 text-sm leading-6 text-[#687e73]">{item.detail}</p><div className="mt-5 flex flex-wrap gap-2">{item.tags.map((tag) => <span key={tag} className="rounded-full bg-[#f1f4ef] px-3 py-1 text-[11px] font-medium text-[#6e8277]">{tag}</span>)}</div><div className="mt-5 border-t border-[#edf0eb] pt-4 text-xs text-[#91a097]">{item.meta}</div></div></article>; })}</div><div className="mt-8 flex items-center justify-between rounded-2xl border border-[#dce5dc] bg-[#eef3ed] px-5 py-4 text-sm text-[#61786c]"><span>點選卡片查看完整介紹，或按 <b className="text-[#bb7654]">＋</b> 加入你的行程</span><span className="hidden sm:block">更新於 2025.04　↗</span></div></section>
      <section id="about" className="border-t border-[#e3e7df] bg-[#f9f8f4] px-5 py-12 text-center sm:py-16"><p className="font-serif text-2xl text-[#18352c]">「山、城、湯與味道，剛好組成熊本。」</p><p className="mt-3 text-sm text-[#8a998f]">下一站，換你寫下自己的旅之しおり。</p></section>
      {active && <div className="fixed inset-0 z-20 flex items-end justify-center bg-[#102d24]/30 p-4 sm:items-center" onClick={() => setActive(null)}><div className="w-full max-w-lg rounded-3xl bg-[#fffdf8] p-7 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><span className="text-xs font-bold uppercase tracking-[0.18em] text-[#bb7654]">No. {active.rank} · {active.kind}</span><h2 className="mt-2 font-serif text-4xl">{active.name}</h2><p className="mt-1 text-sm text-[#91a097]">{active.jp} · {active.area}</p></div><button onClick={() => setActive(null)} className="text-2xl text-[#9aa9a0]" aria-label="關閉">×</button></div><div className={`mt-6 flex h-36 items-center justify-center rounded-2xl bg-gradient-to-br ${active.accent} text-7xl`}>{active.image}</div><p className="mt-6 leading-7 text-[#5f7569]">{active.detail}</p><button onClick={() => { toggle(active.name); setActive(null); }} className="mt-6 w-full rounded-full bg-[#18352c] py-3.5 text-sm font-semibold text-white">{selected.includes(active.name) ? '已加入行程，移除它' : '加入我的行程'}</button></div></div>}
    </main>
  );
}
